In [ ]:
Fundamentals package for scientific computing in python:
    widely utilised in numeric computations

In [ ]:
we will working here with multidimensional data:

In [63]:
import numpy as np #alias names---->numPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays

In [ ]:
Data type:Arrays 

In [100]:
numbers= [2,1,7,8,9.9]

test = np.array(numbers)# this is called n diamensional variable or n daimensional array.


In [101]:
print(numbers)

[2, 1, 7, 8, 9.9]


In [102]:
test = np.array([2,4,4,4])

In [103]:
type(numbers)

list

In [104]:
test

array([2, 4, 4, 4])

In [61]:
type(test) #n diamensional array

numpy.ndarray

In [ ]:
please explain the difference btw list and a numpy arrays?

In [ ]:
ans:arry!!

In [70]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [23]:
type(array_one)

numpy.ndarray

In [109]:
numbers = [10,9,8,7]

array_two= np.array(numbers)
array_two

array([10,  9,  8,  7])

In [121]:
numbers = [10,9,8,7]
numbers1=[5,7,8,8]
array_two= np.array([numbers,numbers1])
array_two

array([[10,  9,  8,  7],
       [ 5,  7,  8,  8]])

In [28]:
#array_ of_zeros

array_of_zeros = np.zeros((3,4))#flot data type!#3*4 #3rows and 4cols

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
array_of_ones = np.ones((4,5))#4rows and 5col...
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
array_eye = np.eye(4)# identity matrices
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#range (start value stop value and step count)
#arange()

In [ ]:
req: i want to print num from 1-50

In [117]:
array_of_numbers= np.arange(1,50,3)#stop is always exclusive here!

array_of_numbers

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [ ]:
req:i want to print even num from 1-50

In [114]:
array_of_even=np.arange(2,50,2) #stop is always exclusive here!

array_of_even

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
req:creating an array of  two dimensions:

In [118]:
array_2d=np.array([(2,3,4),(5,6,7)])
array_2d

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
how to validate the diamension...?

In [122]:
array_2d.shape #shape is considering the rows and coloms. 

(2, 3)

In [124]:
np.arange(0)

array([], dtype=int32)

In [125]:
array_nd=np.arange(6).reshape(3,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [132]:
array_nd=np.arange(6).reshape(5,2)

array_nd

ValueError: cannot reshape array of size 6 into shape (5,2)

In [133]:
a+b

NameError: name 'a' is not defined

In [135]:
array_a=np.array([10,10,10])

array_a

array([10, 10, 10])

In [136]:
array_b=np.array([5,5,5])

array_b

array([5, 5, 5])

In [137]:
a+b

NameError: name 'a' is not defined

In [138]:
array_a+array_b

array([15, 15, 15])

In [139]:
a=np.array([10,10,10])

a


array([10, 10, 10])

In [140]:
b=np.array([5,5,5,])

In [141]:
b

array([5, 5, 5])

In [142]:
a+b

array([15, 15, 15])

In [143]:
a-b

array([5, 5, 5])

In [144]:
a%b

array([0, 0, 0], dtype=int32)

In [145]:
a*b

array([50, 50, 50])

In [146]:
a/b

array([2., 2., 2.])

In [147]:
a<b

array([False, False, False])

In [148]:
a>b

array([ True,  True,  True])